### ISSUE TITLE
Create Header component

### ISSUE THREAD

**Issue by Zukauskas** [front-end-by-rimantas/41-grupe-portfolio-neuron#13]
![image](https://user-images.githubusercontent.com/118177903/210388264-c97dce92-86e6-46fb-8bfe-c0ad50656d6b.png)
it seems to be combined from info at the top and then logo + navigation

**Comment by Deepak9011** [comment]
Good day, Zukauskas
I'd want to work on this problem.
May I do that?

**Comment by Zukauskas** [comment]
> Good day, Zukauskas I'd want to work on this problem. May I do that?

Hey @Deepak9011 , thanks for taking interest in our project. We are not accepting contributors at the moment, because project is for learning purposes only with a full team and mostly based in Lithuanian language. :) We haven't had time to update our README, sorry for misleading :)
